// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: proto/networktrust/service.proto

package networktrust

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTrustBusyReason int32

const (
	CreateTrustBusyReason_CREATE_TRUST_BUSY_REASON_UNSPECIFIED              CreateTrustBusyReason = 0
	CreateTrustBusyReason_CREATE_TRUST_BUSY_REASON_TOO_MANY_ATTEMPTS        CreateTrustBusyReason = 1
	CreateTrustBusyReason_CREATE_TRUST_BUSY_REASON_HANDLING_ANOTHER_REQUEST CreateTrustBusyReason = 2
)

// Enum value maps for CreateTrustBusyReason.
var (
	CreateTrustBusyReason_name = map[int32]string{
		0: "CREATE_TRUST_BUSY_REASON_UNSPECIFIED",
		1: "CREATE_TRUST_BUSY_REASON_TOO_MANY_ATTEMPTS",
		2: "CREATE_TRUST_BUSY_REASON_HANDLING_ANOTHER_REQUEST",
	}
	CreateTrustBusyReason_value = map[string]int32{
		"CREATE_TRUST_BUSY_REASON_UNSPECIFIED":              0,
		"CREATE_TRUST_BUSY_REASON_TOO_MANY_ATTEMPTS":        1,
		"CREATE_TRUST_BUSY_REASON_HANDLING_ANOTHER_REQUEST": 2,
	}
)

func (x CreateTrustBusyReason) Enum() *CreateTrustBusyReason {
	p := new(CreateTrustBusyReason)
	*p = x
	return p
}

func (x CreateTrustBusyReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateTrustBusyReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_networktrust_service_proto_enumTypes[0].Descriptor()
}

func (CreateTrustBusyReason) Type() protoreflect.EnumType {
	return &file_proto_networktrust_service_proto_enumTypes[0]
}

func (x CreateTrustBusyReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateTrustBusyReason.Descriptor instead.
func (CreateTrustBusyReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_networktrust_service_proto_rawDescGZIP(), []int{0}
}

type CreateTrustRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ed25519Pk     *string `protobuf:"bytes,1,opt,name=ed25519_pk,json=ed25519Pk,proto3,oneof" json:"ed25519_pk,omitempty"`
	WireguardPort *uint32 `protobuf:"varint,2,opt,name=wireguard_port,json=wireguardPort,proto3,oneof" json:"wireguard_port,omitempty"`
	DeviceName    *string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3,oneof" json:"device_name,omitempty"`
}

func (x *CreateTrustRequest) Reset() {
	*x = CreateTrustRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_networktrust_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrustRequest) ProtoMessage() {}

func (x *CreateTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_networktrust_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrustRequest.ProtoReflect.Descriptor instead.
func (*CreateTrustRequest) Descriptor() ([]byte, []int) {
	return file_proto_networktrust_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTrustRequest) GetEd25519Pk() string {
	if x != nil && x.Ed25519Pk != nil {
		return *x.Ed25519Pk
	}
	return ""
}

func (x *CreateTrustRequest) GetWireguardPort() uint32 {
	if x != nil && x.WireguardPort != nil {
		return *x.WireguardPort
	}
	return 0
}

func (x *CreateTrustRequest) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

type CreateTrustResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*CreateTrustResponse_Granted
	//	*CreateTrustResponse_Denied
	//	*CreateTrustResponse_Busy
	Response isCreateTrustResponse_Response `protobuf_oneof:"response"`
}

func (x *CreateTrustResponse) Reset() {
	*x = CreateTrustResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_networktrust_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrustResponse) ProtoMessage() {}

func (x *CreateTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_networktrust_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrustResponse.ProtoReflect.Descriptor instead.
func (*CreateTrustResponse) Descriptor() ([]byte, []int) {
	return file_proto_networktrust_service_proto_rawDescGZIP(), []int{1}
}

func (m *CreateTrustResponse) GetResponse() isCreateTrustResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CreateTrustResponse) GetGranted() *CreateTrustGranted {
	if x, ok := x.GetResponse().(*CreateTrustResponse_Granted); ok {
		return x.Granted
	}
	return nil
}

func (x *CreateTrustResponse) GetDenied() *CreateTrustDenied {
	if x, ok := x.GetResponse().(*CreateTrustResponse_Denied); ok {
		return x.Denied
	}
	return nil
}

func (x *CreateTrustResponse) GetBusy() *CreateTrustBusy {
	if x, ok := x.GetResponse().(*CreateTrustResponse_Busy); ok {
		return x.Busy
	}
	return nil
}

type isCreateTrustResponse_Response interface {
	isCreateTrustResponse_Response()
}

type CreateTrustResponse_Granted struct {
	Granted *CreateTrustGranted `protobuf:"bytes,1,opt,name=granted,proto3,oneof"`
}

type CreateTrustResponse_Denied struct {
	Denied *CreateTrustDenied `protobuf:"bytes,2,opt,name=denied,proto3,oneof"`
}

type CreateTrustResponse_Busy struct {
	Busy *CreateTrustBusy `protobuf:"bytes,3,opt,name=busy,proto3,oneof"`
}

func (*CreateTrustResponse_Granted) isCreateTrustResponse_Response() {}

func (*CreateTrustResponse_Denied) isCreateTrustResponse_Response() {}

func (*CreateTrustResponse_Busy) isCreateTrustResponse_Response() {}

type CreateTrustBusy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason *CreateTrustBusyReason `protobuf:"varint,1,opt,name=reason,proto3,enum=networktrust.v1.CreateTrustBusyReason,oneof" json:"reason,omitempty"`
}

func (x *CreateTrustBusy) Reset() {
	*x = CreateTrustBusy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_networktrust_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrustBusy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrustBusy) ProtoMessage() {}

func (x *CreateTrustBusy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_networktrust_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrustBusy.ProtoReflect.Descriptor instead.
func (*CreateTrustBusy) Descriptor() ([]byte, []int) {
	return file_proto_networktrust_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTrustBusy) GetReason() CreateTrustBusyReason {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return CreateTrustBusyReason_CREATE_TRUST_BUSY_REASON_UNSPECIFIED
}

type CreateTrustDenied struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTrustDenied) Reset() {
	*x = CreateTrustDenied{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_networktrust_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrustDenied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrustDenied) ProtoMessage() {}

func (x *CreateTrustDenied) ProtoReflect() protoreflect.Message {
	mi := &file_proto_networktrust_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrustDenied.ProtoReflect.Descriptor instead.
func (*CreateTrustDenied) Descriptor() ([]byte, []int) {
	return file_proto_networktrust_service_proto_rawDescGZIP(), []int{3}
}

type CreateTrustGranted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTrustGranted) Reset() {
	*x = CreateTrustGranted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_networktrust_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTrustGranted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrustGranted) ProtoMessage() {}

func (x *CreateTrustGranted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_networktrust_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrustGranted.ProtoReflect.Descriptor instead.
func (*CreateTrustGranted) Descriptor() ([]byte, []int) {
	return file_proto_networktrust_service_proto_rawDescGZIP(), []int{4}
}

var File_proto_networktrust_service_proto protoreflect.FileDescriptor

var file_proto_networktrust_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74,
	0x72, 0x75, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x2e, 0x76, 0x31, 0x22, 0xbc, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x75, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0a, 0x65, 0x64,
	0x32, 0x35, 0x35, 0x31, 0x39, 0x5f, 0x70, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x09, 0x65, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x50, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x2a,
	0x0a, 0x0e, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x0d, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75,
	0x61, 0x72, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x65, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x5f, 0x70, 0x6b, 0x42,
	0x11, 0x0a, 0x0f, 0x5f, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x6f,
	0x72, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xd8, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x67, 0x72,
	0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x06, 0x64,
	0x65, 0x6e, 0x69, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x06, 0x64, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x04, 0x62, 0x75, 0x73,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x42, 0x75, 0x73, 0x79, 0x48, 0x00, 0x52, 0x04, 0x62, 0x75, 0x73,
	0x79, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x61, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x42, 0x75, 0x73, 0x79,
	0x12, 0x43, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x26, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x42, 0x75,
	0x73, 0x79, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x44,
	0x65, 0x6e, 0x69, 0x65, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x75, 0x73, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x2a, 0xa8, 0x01, 0x0a, 0x15,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x42, 0x75, 0x73, 0x79, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x24, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f,
	0x54, 0x52, 0x55, 0x53, 0x54, 0x5f, 0x42, 0x55, 0x53, 0x59, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f,
	0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x2e, 0x0a, 0x2a, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x52, 0x55, 0x53, 0x54, 0x5f,
	0x42, 0x55, 0x53, 0x59, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x54, 0x4f, 0x4f, 0x5f,
	0x4d, 0x41, 0x4e, 0x59, 0x5f, 0x41, 0x54, 0x54, 0x45, 0x4d, 0x50, 0x54, 0x53, 0x10, 0x01, 0x12,
	0x35, 0x0a, 0x31, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x52, 0x55, 0x53, 0x54, 0x5f,
	0x42, 0x55, 0x53, 0x59, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x48, 0x41, 0x4e, 0x44,
	0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x4e, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x32, 0x6f, 0x0a, 0x13, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x72, 0x75, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x63, 0x65, 0x64, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x6e, 0x71, 0x2f, 0x65, 0x61, 0x61, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_networktrust_service_proto_rawDescOnce sync.Once
	file_proto_networktrust_service_proto_rawDescData = file_proto_networktrust_service_proto_rawDesc
)

func file_proto_networktrust_service_proto_rawDescGZIP() []byte {
	file_proto_networktrust_service_proto_rawDescOnce.Do(func() {
		file_proto_networktrust_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_networktrust_service_proto_rawDescData)
	})
	return file_proto_networktrust_service_proto_rawDescData
}

var file_proto_networktrust_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_networktrust_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_networktrust_service_proto_goTypes = []interface{}{
	(CreateTrustBusyReason)(0),  // 0: networktrust.v1.CreateTrustBusyReason
	(*CreateTrustRequest)(nil),  // 1: networktrust.v1.CreateTrustRequest
	(*CreateTrustResponse)(nil), // 2: networktrust.v1.CreateTrustResponse
	(*CreateTrustBusy)(nil),     // 3: networktrust.v1.CreateTrustBusy
	(*CreateTrustDenied)(nil),   // 4: networktrust.v1.CreateTrustDenied
	(*CreateTrustGranted)(nil),  // 5: networktrust.v1.CreateTrustGranted
}
var file_proto_networktrust_service_proto_depIdxs = []int32{
	5, // 0: networktrust.v1.CreateTrustResponse.granted:type_name -> networktrust.v1.CreateTrustGranted
	4, // 1: networktrust.v1.CreateTrustResponse.denied:type_name -> networktrust.v1.CreateTrustDenied
	3, // 2: networktrust.v1.CreateTrustResponse.busy:type_name -> networktrust.v1.CreateTrustBusy
	0, // 3: networktrust.v1.CreateTrustBusy.reason:type_name -> networktrust.v1.CreateTrustBusyReason
	1, // 4: networktrust.v1.NetworkTrustService.CreateTrust:input_type -> networktrust.v1.CreateTrustRequest
	2, // 5: networktrust.v1.NetworkTrustService.CreateTrust:output_type -> networktrust.v1.CreateTrustResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_networktrust_service_proto_init() }
func file_proto_networktrust_service_proto_init() {
	if File_proto_networktrust_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_networktrust_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrustRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_networktrust_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrustResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_networktrust_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrustBusy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_networktrust_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrustDenied); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_networktrust_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTrustGranted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_networktrust_service_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_networktrust_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CreateTrustResponse_Granted)(nil),
		(*CreateTrustResponse_Denied)(nil),
		(*CreateTrustResponse_Busy)(nil),
	}
	file_proto_networktrust_service_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_networktrust_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_networktrust_service_proto_goTypes,
		DependencyIndexes: file_proto_networktrust_service_proto_depIdxs,
		EnumInfos:         file_proto_networktrust_service_proto_enumTypes,
		MessageInfos:      file_proto_networktrust_service_proto_msgTypes,
	}.Build()
	File_proto_networktrust_service_proto = out.File
	file_proto_networktrust_service_proto_rawDesc = nil
	file_proto_networktrust_service_proto_goTypes = nil
	file_proto_networktrust_service_proto_depIdxs = nil
}
