// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: proto/enginelibrary/events.proto

package enginelibrary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Event_PlaylistHierarchyChanged
	//	*Event_PlaylistsContentChanged
	//	*Event_TrackMetadataChanged
	//	*Event_TrackPerformanceDataChanged
	Data      isEvent_Data `protobuf_oneof:"data"`
	LibraryId *string      `protobuf:"bytes,1,opt,name=library_id,json=libraryId,proto3,oneof" json:"library_id,omitempty"`
	DeviceId  *string      `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_enginelibrary_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enginelibrary_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_enginelibrary_events_proto_rawDescGZIP(), []int{0}
}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Event) GetPlaylistHierarchyChanged() *EventPlaylistHierarchyChanged {
	if x, ok := x.GetData().(*Event_PlaylistHierarchyChanged); ok {
		return x.PlaylistHierarchyChanged
	}
	return nil
}

func (x *Event) GetPlaylistsContentChanged() *EventPlaylistsContentChanged {
	if x, ok := x.GetData().(*Event_PlaylistsContentChanged); ok {
		return x.PlaylistsContentChanged
	}
	return nil
}

func (x *Event) GetTrackMetadataChanged() *EventTrackMetadataChanged {
	if x, ok := x.GetData().(*Event_TrackMetadataChanged); ok {
		return x.TrackMetadataChanged
	}
	return nil
}

func (x *Event) GetTrackPerformanceDataChanged() *EventTrackPerformanceDataChanged {
	if x, ok := x.GetData().(*Event_TrackPerformanceDataChanged); ok {
		return x.TrackPerformanceDataChanged
	}
	return nil
}

func (x *Event) GetLibraryId() string {
	if x != nil && x.LibraryId != nil {
		return *x.LibraryId
	}
	return ""
}

func (x *Event) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_PlaylistHierarchyChanged struct {
	PlaylistHierarchyChanged *EventPlaylistHierarchyChanged `protobuf:"bytes,3,opt,name=playlist_hierarchy_changed,json=playlistHierarchyChanged,proto3,oneof"`
}

type Event_PlaylistsContentChanged struct {
	PlaylistsContentChanged *EventPlaylistsContentChanged `protobuf:"bytes,4,opt,name=playlists_content_changed,json=playlistsContentChanged,proto3,oneof"`
}

type Event_TrackMetadataChanged struct {
	TrackMetadataChanged *EventTrackMetadataChanged `protobuf:"bytes,5,opt,name=track_metadata_changed,json=trackMetadataChanged,proto3,oneof"`
}

type Event_TrackPerformanceDataChanged struct {
	TrackPerformanceDataChanged *EventTrackPerformanceDataChanged `protobuf:"bytes,6,opt,name=track_performance_data_changed,json=trackPerformanceDataChanged,proto3,oneof"`
}

func (*Event_PlaylistHierarchyChanged) isEvent_Data() {}

func (*Event_PlaylistsContentChanged) isEvent_Data() {}

func (*Event_TrackMetadataChanged) isEvent_Data() {}

func (*Event_TrackPerformanceDataChanged) isEvent_Data() {}

type EventAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId  *uint64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	DeviceId *string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id,omitempty"`
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_enginelibrary_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enginelibrary_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_proto_enginelibrary_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventAck) GetEventId() uint64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *EventAck) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

type EventPlaylistHierarchyChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventPlaylistHierarchyChanged) Reset() {
	*x = EventPlaylistHierarchyChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_enginelibrary_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventPlaylistHierarchyChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPlaylistHierarchyChanged) ProtoMessage() {}

func (x *EventPlaylistHierarchyChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enginelibrary_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPlaylistHierarchyChanged.ProtoReflect.Descriptor instead.
func (*EventPlaylistHierarchyChanged) Descriptor() ([]byte, []int) {
	return file_proto_enginelibrary_events_proto_rawDescGZIP(), []int{2}
}

type EventPlaylistsContentChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistId []string `protobuf:"bytes,1,rep,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
}

func (x *EventPlaylistsContentChanged) Reset() {
	*x = EventPlaylistsContentChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_enginelibrary_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventPlaylistsContentChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPlaylistsContentChanged) ProtoMessage() {}

func (x *EventPlaylistsContentChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enginelibrary_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPlaylistsContentChanged.ProtoReflect.Descriptor instead.
func (*EventPlaylistsContentChanged) Descriptor() ([]byte, []int) {
	return file_proto_enginelibrary_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventPlaylistsContentChanged) GetPlaylistId() []string {
	if x != nil {
		return x.PlaylistId
	}
	return nil
}

type EventTrackMetadataChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackMetadata []*TrackMetadata `protobuf:"bytes,1,rep,name=track_metadata,json=trackMetadata,proto3" json:"track_metadata,omitempty"`
}

func (x *EventTrackMetadataChanged) Reset() {
	*x = EventTrackMetadataChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_enginelibrary_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTrackMetadataChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTrackMetadataChanged) ProtoMessage() {}

func (x *EventTrackMetadataChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enginelibrary_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTrackMetadataChanged.ProtoReflect.Descriptor instead.
func (*EventTrackMetadataChanged) Descriptor() ([]byte, []int) {
	return file_proto_enginelibrary_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventTrackMetadataChanged) GetTrackMetadata() []*TrackMetadata {
	if x != nil {
		return x.TrackMetadata
	}
	return nil
}

type EventTrackPerformanceDataChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackPerformanceData []*TrackPerformanceData `protobuf:"bytes,1,rep,name=track_performance_data,json=trackPerformanceData,proto3" json:"track_performance_data,omitempty"`
}

func (x *EventTrackPerformanceDataChanged) Reset() {
	*x = EventTrackPerformanceDataChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_enginelibrary_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTrackPerformanceDataChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTrackPerformanceDataChanged) ProtoMessage() {}

func (x *EventTrackPerformanceDataChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enginelibrary_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTrackPerformanceDataChanged.ProtoReflect.Descriptor instead.
func (*EventTrackPerformanceDataChanged) Descriptor() ([]byte, []int) {
	return file_proto_enginelibrary_events_proto_rawDescGZIP(), []int{5}
}

func (x *EventTrackPerformanceDataChanged) GetTrackPerformanceData() []*TrackPerformanceData {
	if x != nil {
		return x.TrackPerformanceData
	}
	return nil
}

var File_proto_enginelibrary_events_proto protoreflect.FileDescriptor

var file_proto_enginelibrary_events_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x1a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x04, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x6f, 0x0a, 0x1a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x68, 0x69,
	0x65, 0x72, 0x61, 0x72, 0x63, 0x68, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x65, 0x72, 0x61, 0x72, 0x63, 0x68, 0x79, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x48, 0x00, 0x52, 0x18, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69,
	0x73, 0x74, 0x48, 0x69, 0x65, 0x72, 0x61, 0x72, 0x63, 0x68, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x12, 0x6c, 0x0a, 0x19, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x48, 0x00, 0x52, 0x17, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x12, 0x63, 0x0a, 0x16, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x14, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x79, 0x0a, 0x1e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x70,
	0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x1b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x12, 0x22, 0x0a, 0x0a, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x49,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x67, 0x0a, 0x08, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x6c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x65, 0x72, 0x61, 0x72, 0x63, 0x68, 0x79, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x22, 0x3f, 0x0a, 0x1c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x19, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x64, 0x12, 0x46, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x80, 0x01, 0x0a, 0x20,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x12, 0x5c, 0x0a, 0x16, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x50,
	0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x63, 0x65,
	0x64, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6c, 0x69,
	0x6e, 0x71, 0x2f, 0x65, 0x61, 0x61, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_enginelibrary_events_proto_rawDescOnce sync.Once
	file_proto_enginelibrary_events_proto_rawDescData = file_proto_enginelibrary_events_proto_rawDesc
)

func file_proto_enginelibrary_events_proto_rawDescGZIP() []byte {
	file_proto_enginelibrary_events_proto_rawDescOnce.Do(func() {
		file_proto_enginelibrary_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_enginelibrary_events_proto_rawDescData)
	})
	return file_proto_enginelibrary_events_proto_rawDescData
}

var file_proto_enginelibrary_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_enginelibrary_events_proto_goTypes = []interface{}{
	(*Event)(nil),                            // 0: enginelibrary.v1.Event
	(*EventAck)(nil),                         // 1: enginelibrary.v1.EventAck
	(*EventPlaylistHierarchyChanged)(nil),    // 2: enginelibrary.v1.EventPlaylistHierarchyChanged
	(*EventPlaylistsContentChanged)(nil),     // 3: enginelibrary.v1.EventPlaylistsContentChanged
	(*EventTrackMetadataChanged)(nil),        // 4: enginelibrary.v1.EventTrackMetadataChanged
	(*EventTrackPerformanceDataChanged)(nil), // 5: enginelibrary.v1.EventTrackPerformanceDataChanged
	(*TrackMetadata)(nil),                    // 6: enginelibrary.v1.TrackMetadata
	(*TrackPerformanceData)(nil),             // 7: enginelibrary.v1.TrackPerformanceData
}
var file_proto_enginelibrary_events_proto_depIdxs = []int32{
	2, // 0: enginelibrary.v1.Event.playlist_hierarchy_changed:type_name -> enginelibrary.v1.EventPlaylistHierarchyChanged
	3, // 1: enginelibrary.v1.Event.playlists_content_changed:type_name -> enginelibrary.v1.EventPlaylistsContentChanged
	4, // 2: enginelibrary.v1.Event.track_metadata_changed:type_name -> enginelibrary.v1.EventTrackMetadataChanged
	5, // 3: enginelibrary.v1.Event.track_performance_data_changed:type_name -> enginelibrary.v1.EventTrackPerformanceDataChanged
	6, // 4: enginelibrary.v1.EventTrackMetadataChanged.track_metadata:type_name -> enginelibrary.v1.TrackMetadata
	7, // 5: enginelibrary.v1.EventTrackPerformanceDataChanged.track_performance_data:type_name -> enginelibrary.v1.TrackPerformanceData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_enginelibrary_events_proto_init() }
func file_proto_enginelibrary_events_proto_init() {
	if File_proto_enginelibrary_events_proto != nil {
		return
	}
	file_proto_enginelibrary_library_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_enginelibrary_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_enginelibrary_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_enginelibrary_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventPlaylistHierarchyChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_enginelibrary_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventPlaylistsContentChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_enginelibrary_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventTrackMetadataChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_enginelibrary_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventTrackPerformanceDataChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_enginelibrary_events_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Event_PlaylistHierarchyChanged)(nil),
		(*Event_PlaylistsContentChanged)(nil),
		(*Event_TrackMetadataChanged)(nil),
		(*Event_TrackPerformanceDataChanged)(nil),
	}
	file_proto_enginelibrary_events_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_enginelibrary_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enginelibrary_events_proto_goTypes,
		DependencyIndexes: file_proto_enginelibrary_events_proto_depIdxs,
		MessageInfos:      file_proto_enginelibrary_events_proto_msgTypes,
	}.Build()
	File_proto_enginelibrary_events_proto = out.File
	file_proto_enginelibrary_events_proto_rawDesc = nil
	file_proto_enginelibrary_events_proto_goTypes = nil
	file_proto_enginelibrary_events_proto_depIdxs = nil
}
